kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dso202

networking:
  apiServerAddress: "127.0.0.1"
  podSubnet: "10.244.0.0/16"

  serviceSubnet: "10.96.0.0/16"

nodes:
  - role: control-plane

    image: kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5

    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          name: control-plane

    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        listenAddress: "127.0.0.1"
        protocol: TCP

  - role: worker
    image: kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: worker-node-1
          kubeletExtraArgs:
            node-labels: "dso202/node-role=worker,dso202/node-index=1"

  - role: worker
    image: kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: worker-node-2
          kubeletExtraArgs:
            node-labels: "dso202/node-role=worker,dso202/node-index=2"